#!/usr/bin/env perl

# scripts
# 2015-06-01 19:24
# by Ian D Brunton <iandbrunton at gmail dawt com>

use Modern::Perl;

my $client;
my $date = &get_date;
my $type = 'persession';
my $amount = '45.00';
my $method = 'cash';

my $file = $ENV{HOME} . '/Dropbox/docs/training/business/billing-' . $date->{year};
my $datestring = $date->{year} . '-' . $date->{month} . '-' . $date->{day};

for (my $i = 0; $i < $#ARGV; ++$i) {
    if ($ARGV[$i] eq '--client' || $ARGV[$i] eq '-c') {
	$client = $ARGV[++$i];
    }
    elsif ($ARGV[$i] eq '--date') {
	$datestring = $ARGV[++$i];
    }
    elsif ($ARGV[$i] =~ m/\d{4}([\/-])\d{2}\1\d{2}/) {
	$datestring = $ARGV[$i];
    }
    elsif ($ARGV[$i] eq '--type' || $ARGV[$i] eq '-t') {
	$type = $ARGV[++$i];
    }
    elsif ($ARGV[$i] eq '--method' || $ARGV[$i] eq '-m') {
	$method = $ARGV[++$i];
    }
    elsif ($ARGV[$i] eq '--amount' || $ARGV[$i] eq '-a') {
	$amount = $ARGV[++$i];
    }
    else {
    }
}

if (!$client) {
}

open (FILE, ">>", $file) or die ("Cannot open file $file: $!");
print FILE $datestring . '|' . $client . '|session|' . $type . '|' . $amount . '|' . $method . "\n";
close (FILE);

sub get_date {
    my $y = (localtime(time))[5] + 1900;
    my $m = &double_digit((localtime(time))[4] + 1);
    my $d = &double_digit((localtime(time))[3]);

    #return $y . '-' . $m . '-' . $d;
    return { year => $y, month => $m, day => $d };
};

sub double_digit {
    my $n = shift;
    return $n < 10 ? '0' . $n : $n;
}
