#!/bin/bash

cofnfile=$HOME/Dropbox/docs/cofn

if [ $(stat -c "%s" $cofnfile) -gt "0" ] ; then
	if [ -z $1 ] ; then
		#llg -n $(cat $cofnfile) :cof
		mark +C -t to :now
	else
		#llg $(cat $cofnfile) :cof to $1
		mark +C -t to $1
	fi
	echo -n "" > $cofnfile
else
	if [ -z $1 ] ; then
		llg -r :cof :markc
	else
		llg $1 :cof :markc
	fi
	roundtime > $cofnfile
fi
