#!/bin/bash

# Shell script to load log file in editor
# Usage: editlog [-etj] [YYYY/MM/YY] [DIFFERENTIAL]
# Options: -e loads file in alternate editor
#          -t loads training file
#	   -j loads journal file

editor=vi
alternate=emacsclient

if [ -z "$1" ]
then
    $editor "$(clog -f)"
else
    if [ $(expr match "$1" "^-") ]
    then
	if [ $(expr match "$1" "a") ]
	then
	    editor=$alternate
	fi
	args=$(echo "$@" | sed 's/-/-f/' | sed 's/a//')
    else
	args="-f $@"
    fi
    
    action=$(clog $args)
    
    if [ -e "$action" ]
    then
    	$editor "$action"
    else
    	echo "File $action does not exist"
    fi
fi
exit 0
