#!/bin/sh

if [ -z "$1" ]
then
	echo "File type not specified, dumbass."
	exit 1
fi

FILETYPE=$1

if [ -z "$2" ]
then
	FILENAME=$FILETYPE
else
	FILENAME=$2
fi

if [ -e $_PWD/$FILENAME ]
then
	echo "File $FILENAME already exists."
	exit 1
fi

_PWD=`pwd`
PROJECT=`basename $_PWD`
DATE=`date +"%Y-%m-%d %H:%M"`
UC_FILENAME=`echo $FILENAME | tr [a-z.] [A-Z_]`

if [ -e $HOME/templates/$type ]
then
	sed 's/#PROJECT#/'"$PROJECT"'/g
	s/#FILENAME#/'"$FILENAME"'/g
	s/#UC_FILENAME#/'"$UC_FILENAME"'/g
	s/#DATE#/'"$DATE"'/g' <$HOME/templates/$FILETYPE >$FILENAME
else
    echo 'No template for type `'$type"'"
    exit 1
fi

exit 0
