#!/usr/bin/env perl

# scripts
# 2017-07-14 15:25
# by Ian D Brunton <iandbrunton at gmail dawt com>

use Modern::Perl;
use IDB;
use File::Copy qw(move);

my $file = $ENV{HOME} . '/Dropbox/docs/training/business/payperiod';
my $archive = $file . '-archive/';

if (! -e $archive ) { mkdir $archive; }

my $date = join ('-', &IDB::year ((localtime(time))[5]),
		    &IDB::double_digit ((localtime(time))[4] + 1),
		    &IDB::double_digit ((localtime(time))[3]));
my $wkday = &IDB::wkday ((localtime)[6]);

if ($ARGV[0] =~ /cheque/) {
    # Begin new pay period.  Move current file to archive.
    my $archivefile = $archive . $date;
    move ($file, $archivefile);

    my $total = 0;
    my $count = 0;
    open (FILE, "<", $archivefile) or die ("Cannot open file `$archivefile': $!");
    my @lines = <FILE>;
    close (FILE);

    foreach (@lines) {
	if ($_ =~ /(\d+(\.\d+)?)$/ && $_ !~ /^#/) {
	    ++$count;
	    $total += $1;
	}
    }

    open (FILE, ">>", $archivefile) or die ("Cannot open file `$archivefile': $!");
    print FILE "\nTotal:\t$total\n";
    print FILE "Hours:\t$count\n";
    close (FILE);
}
elsif ($ARGV[0] =~/^\d+(\.\d+)?$/) {
    # Add 1 session at pay rate given in $ARGV[0]
    my $rate = shift (@ARGV);
    my $ord = shift (@ARGV);
    my $client = "unknown";
    if (@ARGV) { $client = join (' ', @ARGV); }
    open (FILE, ">>", $file) or die ("Cannot open file `$file': $!");
    print FILE $date, ' ', $wkday, "\t",
	$client, "\t",
	$ord, "\t",
	$rate, "\n";
    close (FILE);
}
else { # incorrect input: error
    die ("Invalid input.  Try again.");
}
