#!/usr/bin/env perl

# scripts
# 2017-07-14 15:25
# by Ian D Brunton <iandbrunton at gmail dawt com>

use Modern::Perl;
use IDB;
use File::Copy qw(move);

my $file = $ENV{HOME} . '/Dropbox/docs/training/business/payperiod';

my $date = join ('-', &IDB::year ((localtime(time))[5]),
		    &IDB::double_digit ((localtime(time))[4] + 1),
		    &IDB::double_digit ((localtime(time))[3]));
my $wkday = &IDB::wkday ((localtime)[6]);

my $type = shift (@ARGV);
my $rate = shift (@ARGV);
my $ord = shift (@ARGV) || '1/1';
my $client = join (@ARGV) || $type;

$file .= '-' . $type;

$rate = sprintf ("%.2f", $rate);

open (FILE, ">>", $file) or die ("Cannot open file `$file': $!");
print FILE $date, ' ', $wkday, "\t",
    $client, "\t",
    $ord, "\t",
    $rate, "\n";
close (FILE);

exit (0);

__END__;

payperiod motiv 22.05 1/12 Judy Saunders
payperiod iwk 75.00 1/1
